### ISSUE TITLE
network security group name should it include location too?

### ISSUE THREAD

**Issue by mandsa01** [Azure-Terraform/terraform-azurerm-virtual-network#22]
for one of our use case where we are creating the failover kubernetes cluster and vnet in a different region under same resource group.
as part of this module it creates the nsg rules too, which takes just the subnet type into account for naming, so i had to name the subnet type different to that of already existing one under different subnet as a work around, do you think location should also be included to the nsg name?

**Comment by nikuljain** [comment]
/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/networkSecurityGroups/app-xxx-iaas-private-security-group" already exists - to be managed via Terraform this resource needs to be imported into the State. 

as the naming scope is RG specific and we are having another vnet in DR region , it is giving above error , please do correct if the understanding doesn't make sense

**Comment by fabiendelpierre** [comment]
I think I understand the issue, but I would suggest that you simply don't put your DR resources under the same resource group.

RGs are region-specific and both the name of the RG and its metadata include the region name. By putting your DR in the same RG, that would mean for example having a resource group in East US named "app-awesomesoftware-prod-eastus" that would contain resources in East US *and* resources in a different region. Seems confusing.

**Comment by nikuljain** [comment]
There is no specific reason in staying same RG , we didn't had any real answers to split in two RG , rather than just one ,
we will create RG per region and proceed ahead

**Comment by fabiendelpierre** [comment]
Sounds good. I'll close this then and from the discussion in the naming repo it sounds like everything is clear but feel free to reopen this as needed.
