### ISSUE TITLE
Original Error: Code="NetcfgInvalidSubnet"

### ISSUE THREAD

**Issue by faraday23** [Azure-Terraform/terraform-azurerm-virtual-network#23]
### Expected Behavior

I'm trying to create a subnet with the module, I've run into this error with existing vnet's.

@dutsmiller  Could this module _also_ be used to create subnet's within an existing vnet or no?

### Actual Behavior

throws error (see Error output)

### Error Output

```hcl
Error: creating/updating Subnet: (Name "private-link-endpoint" / Virtual Network Name "aks-vnet-24970181" / Resource Group "MC_app-missouri-sandbox-eastus2_aks-app-missouri-sandbox-eastus2_eastus2"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="NetcfgInvalidSubnet" Message="Subnet 'private-link-endpoint' is not valid in virtual network 'aks-vnet-24970181'." Details=[]

  on .terraform\modules\subnet_private_link\subnet\main.tf line 1, in resource "azurerm_subnet" "subnet":
   1: resource "azurerm_subnet" "subnet" {
```

### Affected Resource(s)

* `azurerm_v2.55.0`
* `terraform v0.14.8`

### Terraform Configuration Files

**Main.tf**  
```hcl
module "subnet_private_link" {
  source = "github.com/Azure-Terraform/terraform-azurerm-virtual-network.git///subnet?ref=v2.7.0"

  naming_rules = module.naming.yaml

  resource_group_name = "MC_app-missouri-sandbox-eastus2_aks-app-missouri-sandbox-eastus2_eastus2"
  location            = module.metadata.location
  names               = module.metadata.names
  tags                = module.metadata.tags

  virtual_network_name = data.azurerm_virtual_network.vnet.name
  enforce_private_link_endpoint_network_policies = true
  enforce_subnet_names = false

  cidrs       = ["redacted"]
  subnet_type = "private-link-endpoint"

  allow_lb_inbound        = false 
  allow_internet_outbound = false 
  allow_vnet_outbound     = false 
  allow_vnet_inbound      = false 
}
```

**Comment by dutsmiller** [comment]
Why are you trying to create resources within the kubernetes resource group?  Isn't "MC_app-missouri-sandbox-eastus2_aks-app-missouri-sandbox-eastus2_eastus2" the one that AKS creates for its own use?  If so, I would STRONGLY recommend against creating anything inside that.  Also, why is the vnet name coming from a data resource (  virtual_network_name = data.azurerm_virtual_network.vnet.name )?  Are you trying to use the AKS created virtual network?
