### ISSUE TITLE
Deprecated arguments

### ISSUE THREAD

**Issue by feltem01** [Azure-Terraform/terraform-azurerm-virtual-network#50]
Hi,

We are getting this warning whenever we run a plan/apply on TFE due a deprecated argument:

![image](https://github.com/Azure-Terraform/terraform-azurerm-virtual-network/assets/89923179/47c1a1a7-8cb0-4efa-ab33-b06bccdd0fc0)

![image](https://github.com/Azure-Terraform/terraform-azurerm-virtual-network/assets/89923179/ecc41b98-1d4f-4072-88d7-f524d0220341)

I'd like to suggest replacing the argument by `private_endpoint_network_policies_enabled` and `private_link_service_network_policies_enabled`.
Reference: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet#private_endpoint_network_policies_enabled
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet#private_link_service_network_policies_enabled

**Comment by fabiendelpierre** [comment]
Closed by #51.
